[project]
name = "fspacker"
description = "Fast & Simple Packer toolset for python."
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.7",
    "pkginfo>=1.11.2",
    "requests>=2.32.3",
    "rtoml>=0.11.0",
    "stdlib-list>=0.10.0",
    "types-requests>=2.32.0.20241016",
]
[project.urls]
source = "https://gitee.com/gooker_young/fspacker"

[project.scripts]
fsp = "fspacker.__main__:main"

[project.entry-points."pipx.run"]
fsp = "fspacker.__main__:main"

[tool.uv]
index-url = 'https://pypi.tuna.tsinghua.edu.cn/simple/'
dev-dependencies = [
    "coverage>=7.6.1",
    "mypy>=1.13.0",
    "pip>=24.2",
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
    "ruff>=0.7.3",
    "fspacker",
    "pyside2>=5.15.2.1",
    "pypdf>=5.1.0",
    "pandas>=2.0.3",
    "numpy>=1.24",
    "matplotlib>=3.7.5",
    "py7zr>=0.22.0",
    "setuptools>=75.3.0",
    "pytest-benchmark>=4.0.0",
    "pysnooper>=1.2.1",
    "black>=24.8.0",
    "tox>=4.23.2",
    "poetry>=1.8.4",
    "jieba>=0.42.1",
    "pyyaml>=6.0.2",
    "lxml>=5.3.0",
    "ordered-set>=4.1.0",
    # for docs
    "sphinx>=7.1.2",
    "sphinx-autodoc-typehints>=2.0.1",
    "pytest-html>=4.1.1",
    "psutil>=6.1.1",
]

[tool.uv.sources]
fspacker = { workspace = true }

[tool.ruff]
line-length = 120 # 代码最大行宽
lint.select = [# 选择的规则
    "F",
    "E",
    "W",
    "UP",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
test = [
    "psutil>=6.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/fspacker"]

[tool.hatch.version]
path = "src/fspacker/__init__.py"
