requires = ["tox>=4"]
env_list = ["lint", "type", "build", "publish"]

[testenv]
deps = ["pytest", "pytest-cov", "pytest-html", "psutil"]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]
setenv = "PIP_INDEX_URL = https://pypi.tuna.tsinghua.edu.cn/simple/"

[pytest]
addopts = ["--benchmark-enable"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8",
    "pytest-sugar"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.type]
description = "run type checks"
deps = ["mypy"]
commands = [["mypy", { replace = "posargs", default = ["fspacker"], extend = true }]]

[env.build]
description = "build & publish"
deps = ["poetry"]
commands = [
    ["poetry", "build", { replace = "posargs", extend = true }],
    ["poetry", "publish", { replace = "posargs", extend = true }],
]


