import dataclasses
import pathlib
import typing

__all__ = [
    "BuildTarget",
    "BuildConfig",
]


@dataclasses.dataclass
class BuildTarget:
    src: pathlib.Path
    deps: typing.List[pathlib.Path]
    ast: typing.Set[str]

    def __repr__(self):
        return f"[src={self.src.name}, ast={self.ast}, deps={self.deps}]"


@dataclasses.dataclass
class BuildConfig:
    """Build config generated by parser"""

    targets: typing.Dict[str, BuildTarget]
