name: Rust and Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"

      - name: Install Python dependencies
        run: |
          cd python
          pip install --upgrade pip
          pip install uv
          python3 -m uv sync

      - name: Run Python tests
        run: |
          pytest

      - name: Publish Python package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          uv build
          uv push
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
